[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/submit-form"
  to = "/.netlify/functions/submit-form"
  status = 200
